<a href="https://colab.research.google.com/github/seungmin001/prac_deeplearningzerotoall/blob/main/Lab6_Softmax_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
# multinomial classification
import tensorflow as tf
import numpy as np

# Data
x_data= np.array([ # 4 features, 8 data
    [1,2,1,1],
    [2,1,3,2],
    [3,1,3,4],
    [4,1,5,5],
    [1,7,5,5],
    [1,2,5,6],
    [1,6,6,6],
    [1,7,7,7]
], dtype=np.float32)

y_data = np.array([ # 3 label, 8 data
    [0,0,1],
    [0,0,1],
    [0,0,1],
    [0,1,0],
    [0,1,0],
    [0,1,0],
    [1,0,0],
    [1,0,0],
], dtype=np.float32)

nb_classes = 3 # num of classes


# Weight, bias
W = tf.Variable(tf.random.normal([4,3]), name='Weight')
b = tf.Variable(tf.random.normal([1]), name='bias')


########
# raw code

# hypothesis = 일차함수 W*X + b, softmax로 y값 확률으로 바꾸기
hypothesis = tf.nn.softmax(tf.matmul(x_data,W)+b)
print(hypothesis)

# cost function : cross entropy
cost = tf.reduce_mean( - tf.reduce_sum(y_data * tf.math.log(hypothesis), axis=1))
print(cost)

# optimizer (Gradient Descent에 사용되는 도구)
optimizer= tf.keras.optimizers.SGD(learning_rate=0.01)


tf.Tensor(
[[6.8918709e-03 1.4897143e-02 9.7821099e-01]
 [1.1290295e-04 3.5197347e-05 9.9985182e-01]
 [1.6917064e-06 1.2495858e-07 9.9999821e-01]
 [1.3066833e-08 3.6102327e-10 1.0000000e+00]
 [1.9248882e-10 4.8596608e-08 1.0000000e+00]
 [9.3114583e-10 1.7193391e-09 1.0000000e+00]
 [1.2788758e-11 1.2434965e-09 1.0000000e+00]
 [1.9733760e-13 4.9706475e-11 1.0000000e+00]], shape=(8, 3), dtype=float32)
tf.Tensor(14.140202, shape=(), dtype=float32)


In [33]:
###############################################################################
# 함수 형태로 작성

# softmax hypothesis
def hypothesis(X): 
    base = tf.matmul(X,W) + b
    return tf.nn.softmax(base)

hypothesis(x_data)

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[6.8918709e-03, 1.4897143e-02, 9.7821099e-01],
       [1.1290295e-04, 3.5197347e-05, 9.9985182e-01],
       [1.6917064e-06, 1.2495858e-07, 9.9999821e-01],
       [1.3066833e-08, 3.6102327e-10, 1.0000000e+00],
       [1.9248882e-10, 4.8596608e-08, 1.0000000e+00],
       [9.3114583e-10, 1.7193391e-09, 1.0000000e+00],
       [1.2788758e-11, 1.2434965e-09, 1.0000000e+00],
       [1.9733760e-13, 4.9706475e-11, 1.0000000e+00]], dtype=float32)>

In [34]:
# cost func : cross-entropy
def cost_func(X,Y):
    logits=hypothesis(X)
    cost_raw = - tf.reduce_sum( Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost_raw)
    return cost_mean

cost_func(x_data,y_data)

<tf.Tensor: shape=(), dtype=float32, numpy=14.140202>

In [35]:

# gradient
def grad_func(X,Y):
    with tf.GradientTape() as tape:
        cost=cost_func(X,Y)
        grads=tape.gradient(cost, [W,b])
        return grads

grad_func(x_data, y_data)

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[-0.24910966, -0.748129  ,  0.99723864],
        [-1.6232626 , -1.2462714 ,  2.869534  ],
        [-1.6240956 , -1.8731247 ,  3.49722   ],
        [-1.6241095 , -1.9981289 ,  3.6222386 ]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-4.4703484e-08], dtype=float32)>]

In [36]:

# optimizer (Gradient Descent에 사용되는 도구)
optimizer= tf.keras.optimizers.SGD(learning_rate=0.01)

epoch = 5000

for step in range(epoch+1):
    # cost계산
    # with tf.GradientTape() as tape:
    #    cost = tf.reduce_mean( - tf.reduce_sum(y_data * tf.math.log(hypothesis), axis=1))
        
    # cost 함수에 대한 W,b의 기울기 
    # grads = tape.gradient(cost, variables)

    grads=grad_func(x_data, y_data)
    # 기울기 gradient descent 적용
    optimizer.apply_gradients(zip(grads,[W,b]))

    if step % 500 == 0:
        print("{:5} | {:12.5f}".format(step, cost_func(x_data,y_data)))


    0 |     13.61860
  500 |      0.73716
 1000 |      0.63475
 1500 |      0.58228
 2000 |      0.54747
 2500 |      0.52125
 3000 |      0.50002
 3500 |      0.48202
 4000 |      0.46629
 4500 |      0.45222
 5000 |      0.43945
